
BIN=mtbx_wavgen.exe

MODULE_HEADER=$(MY_AUDIO_ROOT)/Programs/Include/mtbx/WaveGen.h
MODULE_SRC=WaveGen.cpp

INC=$(MODULE_HEADER)

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
