
BIN=mtbx_wavgen.exe

MODULE_HEADER=$(SELF_LEARNING_INCDIR)/mtbx/WaveGen.h
MODULE_SRC=WaveGen.cpp

INC=$(MODULE_HEADER)

LIBS=-lmcon

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
