BIN=estimater

MODULE_HEADER=
MODULE_SRC=

INC=$(MODULE_HEADER) Common.h
SRC=Setup.cpp Cleanup.cpp PreProcess.cpp Process.cpp PostProcess.cpp

LIBS=-lmfio -lmasp -lmcon

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
