#ifndef _STATUS_H_
#define _STATUS_H_

#define NO_ERROR 0
#define ERROR_NULL 1
#define ERROR_NOT_FOUND 2
#define ERROR_UNKNOWN 3
#define ERROR_ILLEGAL 4
#define ERROR_CANNOT_ALLOCATE_MEMORY 5
#define ERROR_NOT_ENOUGH 6
#define ERROR_ILLEGAL_PERMISSION 7
#define ERROR_CANNOT_OPEN_FILE 8
#define ERROR_UNSUPPORTED 9
#define ERROR_INVALID_HANDLE 10

#endif // #ifndef _STATUS_H_
