
BIN=mutl_interp

LIBS=-lmfio

INC=$(addprefix, $(SELF_LEARNING_INCDIR)/mutl, Spline.h Linear.h)
MODULE_SRC=Spline.cpp Linear.cpp

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
