BIN=mcon_matrix.exe

INC=$(SELF_LEARNING_INCDIR)/mcon/Matrix.h
SRC=../Vectord/Vectord.cpp ../Vectord/VectordBase.cpp

CPPFLAGS += -O3

WARNINGS +=  \
	-Werror \

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
