BIN=mcon_matrix.exe

MODULE_HEADER=Matrix.h
MODULE_SRC=

INC=$(MODULE_HEADER)

INCDIRS += \
	../Vector  \
	../Vectord  \

LIBS=

CPPFLAGS += -O3

WARNINGS +=  \
	-Werror \

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
