
BIN=resampler.exe
LIB=libsrc.a
LIBS=-lwin -lfir -lfio -lfft

MODULE_HEADER=Resampler.h
MODULE_SRC=Resampler.cpp

INC=$(MODULE_HEADER)

CPPFLAGS += -O3

include $(MY_AUDIO_ROOT)/Build/Make/modulerules.mk
