
BIN=masp_resampler
LIBS=-lmasp -lmfio -lmcon

MODULE_HEADER=$(SELF_LEARNING_INCDIR)/masp/Resampler.h
MODULE_SRC=Resampler.cpp

INC=$(MODULE_HEADER)

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
