
BIN=masp_iir
LIBS=-lmcon -lmfio -lmtbx

MODULE_HEADER=$(SELF_LEARNING_INCDIR)/masp/Iir.h
MODULE_SRC=Iir.cpp

INC=$(MODULE_HEADER)

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
