BIN=masp_ft.exe

MODULE_HEADER=Ft.h
MODULE_SRC=Ft.cpp

INC=$(MODULE_HEADER)
SRC=test_Ft.cpp benchmark_Ft.cpp

LIBS=-ltbx -lutl -lfio

CPPFLAGS += -O3

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
