BIN=mfio_wave

INC=$(addprefix $(SELF_LEARNING_INCDIR)/mfio/, Wave.h)
MODULE_SRC=Wave.cpp

LIBS=-lmtbx

CPPFLAGS += -O3

WARNINGS +=  \
	-Werror \

include $(SELF_LEARNING_ROOT)/Build/Make/modulerules.mk
